drop table offer if exists;
drop table application if exists;
drop table application_status if exists;

CREATE TABLE IF NOT EXISTS offer (
 id bigint(20) NOT NULL generated by default as identity(start with 1),
 offer_uuid varchar(100),
 job_title varchar(200) NOT NULL UNIQUE,
 start_date timestamp,
 no_of_applications bigint(20),
 PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS application (
 id bigint(20) NOT NULL generated by default as identity(start with 1),
 application_uuid varchar(100),
 email_id varchar(200) NOT NULL,
 resume varchar(10000),
 current_application_status varchar(20),
 offer_id bigint(20),
 PRIMARY KEY(id)
);

ALTER TABLE application
ADD CONSTRAINT fk_application_offer
FOREIGN KEY (offer_id) REFERENCES offer(id);

-- The below tables are event store and can kept in a seperated database.

CREATE TABLE IF NOT EXISTS application_event_store (
 id bigint(20) NOT NULL generated by default as identity(start with 1),
 name varchar(100),
 application_status varchar(20),
 application_uuid varchar(100),
 creation_date timestamp,
 offer_uuid varchar(100),
 payload varchar(1000),
 PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS offer_event_store (
 id bigint(20) NOT NULL generated by default as identity(start with 1),
 name varchar(100),
 creation_date timestamp,
 offer_uuid varchar(100),
 payload varchar(1000),
 PRIMARY KEY(id)
);








